In [24]:
import numpy as np
import gym
import random
import time
from IPython.display import clear_output

Creating the environment

In [25]:
env = gym.make("FrozenLake-v0")

[2020-01-13 15:22:45,367] Making new env: FrozenLake-v0


Creating the Q-table

In [26]:
action_space_size = env.action_space.n
state_space_size = env.observation_space.n

q_table = np.zeros((state_space_size, action_space_size))

In [27]:
print(q_table)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


Initializing Q-learning parameters

In [28]:
num_episodes = 10000
max_steps_per_episode = 100

learning_rate = 0.1
discount_rate = 0.99

exploration_rate = 1
max_exploration_rate = 1
min_exploration_rate = 0.01
exploration_decay_rate = 0.001

Coding the Q-learning algorithm training loop

In [29]:
rewards_all_episodes = []
# Q-learning algorithm
for episode in range(num_episodes):
    # initialize new episode params
    state = env.reset()
    done = False
    rewards_current_episode = 0
    
    for step in range(max_steps_per_episode): 
        # Exploration-exploitation trade-off
        exploration_rate_threshold = random.uniform(0, 1)
        if exploration_rate_threshold > exploration_rate:
            action = np.argmax(q_table[state,:]) 
        else:
            action = env.action_space.sample()
        # Take new action
        new_state, reward, done, info = env.step(action)
        # Update Q-table
        q_table[state, action] = q_table[state, action] * (1 - learning_rate) + learning_rate * (reward + discount_rate * np.max(q_table[new_state, :]))
        # Set new state
        state = new_state
        # Add new reward 
        rewards_current_episode += reward 
        
        if done == True:
            break

    # Exploration rate decay
    exploration_rate = min_exploration_rate + (max_exploration_rate - min_exploration_rate) * np.exp(-exploration_decay_rate*episode)
    # Add current episode reward to total rewards list
    rewards_all_episodes.append(rewards_current_episode)
    

After all episodes complete

In [30]:
rewards_per_thosand_episodes = np.split(np.array(rewards_all_episodes),num_episodes/1000)
count = 1000

In [31]:
print("********Average reward per thousand episodes********\n")
for r in rewards_per_thosand_episodes:
    print(count, ": ", str(sum(r/1000)))
    count += 1000

********Average reward per thousand episodes********

1000 :  0.058000000000000045
2000 :  0.21900000000000017
3000 :  0.4100000000000003
4000 :  0.5310000000000004
5000 :  0.6130000000000004
6000 :  0.6570000000000005
7000 :  0.6780000000000005
8000 :  0.6360000000000005
9000 :  0.6450000000000005
10000 :  0.6810000000000005


Interpreting the training results

In [32]:
# Print updated Q-table
print("\n\n********Q-table********\n")
print(q_table)



********Q-table********

[[0.52229493 0.49960767 0.5103047  0.50717923]
 [0.33749301 0.22610635 0.28608605 0.44495712]
 [0.35492839 0.29537499 0.27274557 0.27777709]
 [0.17322575 0.04437863 0.02615546 0.07578993]
 [0.53878046 0.31224824 0.30926115 0.24935421]
 [0.         0.         0.         0.        ]
 [0.25922088 0.16467649 0.14336379 0.09253269]
 [0.         0.         0.         0.        ]
 [0.35836678 0.42126618 0.44563235 0.56936897]
 [0.39513359 0.58919697 0.36692929 0.35824741]
 [0.48977479 0.42746016 0.46147613 0.31099974]
 [0.         0.         0.         0.        ]
 [0.         0.         0.         0.        ]
 [0.43190917 0.61197125 0.68347116 0.58912322]
 [0.73408479 0.81234425 0.71158425 0.72795444]
 [0.         0.         0.         0.        ]]


SFFF

FHFH

FFFH

HFFG

https://deeplizard.com/learn/video/ZaILVnqZFCg

In [33]:
# Watch our agent play Frozen Lake by playing the best action 
# from each state according to the Q-table

for episode in range(3):
    # initialize new episode params
    state = env.reset()
    done = False
    print("*****EPISODE ", episode+1, "*****\n\n\n\n")
    time.sleep(1)

    for step in range(max_steps_per_episode):        
        # Show current state of environment on screen
        clear_output(wait=True)
        env.render()
        time.sleep(0.3)

        # Choose action with highest Q-value for current state
        action = np.argmax(q_table[state,:])        

        # Take new action
        new_state, reward, done, info = env.step(action)

        if done:
            clear_output(wait=True)
            env.render()
            if reward == 1:
                # Agent reached the goal and won episode
                print("****You reached the goal!****")
                time.sleep(3)
            else:
                # Agent stepped in a hole and lost episode
                print("****You fell through a hole!****")
                time.sleep(3)
            clear_output(wait=True)
            break

        # Set new state
        state = new_state

env.close()

  (Down)
SFFF
FHFH
FFFH
HFFG
****You reached the goal!****
